# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d99057aae8cb4311032b1fcb51ec674521ab6de0687817318f75f49f404f10a802bbd299af3fea049b90e5ba7d999a24c071cd0e5ac4b743352ddd9e672143

test:
  secret_key_base: e8d2fd6e7fc7bdae5449ed13a9b16a55e55f282cb0d43e9823984205167f1d5b8e3041d4ef478db2fc5ceb4d395720c6abdef5aa5a3bff92de8ffba4eef7aa3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
